#Farmaco.create(:farmaco=>'ÁCIDO VALPRÓICO 300mg',:forma_id=>1,:controlado=>true)
#Farmaco.create(:farmaco=>'AMITRIPTILINA 25mg',:forma_id=>1,:controlado=>true)
Farmaco.create(:farmaco=>'ATRACÚRIO (TRACUR) 10mg/ml',:forma_id=>2,:controlado=>true)
Farmaco.create(:farmaco=>'BIPERIDENO 5mg/ml',:forma_id=>2,:controlado=>true)
Farmaco.create(:farmaco=>'BROMAZEPAM 6mg',:forma_id=>1,:controlado=>true)
Farmaco.create(:farmaco=>'BROMAZEPAM 3mg',:forma_id=>1,:controlado=>true)
Farmaco.create(:farmaco=>'CARBAMAZEPINA 200mg',:forma_id=>1,:controlado=>true)
Farmaco.create(:farmaco=>'CARBONATO DE LÍTIO 300mg',:forma_id=>1,:controlado=>true)
Farmaco.create(:farmaco=>'CETAMINA 50mg/ml',:forma_id=>2,:controlado=>true)
Farmaco.create(:farmaco=>'CLONAZEPAM 0,5mg',:forma_id=>1,:controlado=>true)
Farmaco.create(:farmaco=>'CLONAZEPAM 2mg',:forma_id=>1,:controlado=>true)
Farmaco.create(:farmaco=>'CLONAZEPAM 2,5mg/ml',:forma_id=>4,:controlado=>true)
Farmaco.create(:farmaco=>'CLORPROMAZINA 5mg/ml',:forma_id=>2,:controlado=>true)
Farmaco.create(:farmaco=>'CLORPROMAZINA 100mg',:forma_id=>1,:controlado=>true)
Farmaco.create(:farmaco=>'CLORPROMAZINA 200mg/ml',:forma_id=>1,:controlado=>true)
Farmaco.create(:farmaco=>'CLORPROMAZINA 40mh/ml',:forma_id=>4,:controlado=>true)
Farmaco.create(:farmaco=>'CODEÍNA/PARACETAMOL 7,5/500mg',:forma_id=>1,:controlado=>true)
Farmaco.create(:farmaco=>'CODEÍNA/PARACETAMOL 30/500mg',:forma_id=>1,:controlado=>true)
Farmaco.create(:farmaco=>'DIAZEPAM 5 mg',:forma_id=>1,:controlado=>true)
Farmaco.create(:farmaco=>'DIAZEPAM 5mg/ml',:forma_id=>2,:controlado=>true)
Farmaco.create(:farmaco=>'DIAZEPAM 10mg',:forma_id=>1,:controlado=>true)
Farmaco.create(:farmaco=>'DOLANTINA (PETIDINA) 50mg/ml',:forma_id=>2,:controlado=>true)
Farmaco.create(:farmaco=>'ETOMIDATO 2mg/ml',:forma_id=>2,:controlado=>true)
Farmaco.create(:farmaco=>'FENITOINA 50mg/ml',:forma_id=>2,:controlado=>true)
Farmaco.create(:farmaco=>'FENITOÍNA 50mg',:forma_id=>1,:controlado=>true)
Farmaco.create(:farmaco=>'FENITOÍNA 100mg',:forma_id=>1,:controlado=>true)
Farmaco.create(:farmaco=>'FENOBARBITAL 200mg/ml',:forma_id=>2,:controlado=>true)
Farmaco.create(:farmaco=>'FENOBARBITAL 40mg/ml',:forma_id=>4,:controlado=>true)
Farmaco.create(:farmaco=>'FENOBARBITAL 100mg',:forma_id=>1,:controlado=>true)
Farmaco.create(:farmaco=>'FENOBARBITAL 100mg/ml',:forma_id=>2,:controlado=>true)
Farmaco.create(:farmaco=>'FENTALINA 0,05mg/ml (amp 10ml)',:forma_id=>2,:controlado=>true)
Farmaco.create(:farmaco=>'FENTALINA 0,05mg/ml (amp 5ml)',:forma_id=>2,:controlado=>true)
Farmaco.create(:farmaco=>'FENTALINA 0,05mg/ml (amp 2 ml)',:forma_id=>2,:controlado=>true)
Farmaco.create(:farmaco=>'FLUMAZENIL 0.1mg/ml/0.5mg/5ml',:forma_id=>2,:controlado=>true)
Farmaco.create(:farmaco=>'FLUOXETINA 20mg',:forma_id=>1,:controlado=>true)
Farmaco.create(:farmaco=>'HALOPERIDOL 2mg/ml',:forma_id=>4,:controlado=>true)
Farmaco.create(:farmaco=>'HALOPERIDOL 5mg/ml',:forma_id=>2,:controlado=>true)
Farmaco.create(:farmaco=>'HALOPERIDOL 5mg',:forma_id=>1,:controlado=>true)
Farmaco.create(:farmaco=>'HALOPERIDOL 2mg/2ml',:forma_id=>4,:controlado=>true)
Farmaco.create(:farmaco=>'METADONA 10mg',:forma_id=>1,:controlado=>true)
Farmaco.create(:farmaco=>'MIDAZOLAM 5mg/ml',:forma_id=>2,:controlado=>true)
Farmaco.create(:farmaco=>'MIDAZOLAM 15mg/ml',:forma_id=>2,:controlado=>true)
Farmaco.create(:farmaco=>'MIDAZOLAM    15mg',:forma_id=>1,:controlado=>true)
Farmaco.create(:farmaco=>'MISOPROSTOL 25mcg',:forma_id=>1,:controlado=>true)
Farmaco.create(:farmaco=>'MORFINA 0,2mg/ml',:forma_id=>2,:controlado=>true)
Farmaco.create(:farmaco=>'MORFINA 10mg/ml',:forma_id=>2,:controlado=>true)
Farmaco.create(:farmaco=>'MORFINA 1mg/ml',:forma_id=>2,:controlado=>true)
Farmaco.create(:farmaco=>'MORFINA 30mg',:forma_id=>1,:controlado=>true)
Farmaco.create(:farmaco=>'MORFINA 10mg',:forma_id=>1,:controlado=>true)
Farmaco.create(:farmaco=>'MORFINA (USO ESPINHAL) 0,2mg/ml',:forma_id=>2,:controlado=>true)
Farmaco.create(:farmaco=>'NALOXONA 0,4mg/ml',:forma_id=>2,:controlado=>true)
Farmaco.create(:farmaco=>'PROPOFOL 10mg/ml 10ml',:forma_id=>2,:controlado=>true)
Farmaco.create(:farmaco=>'PROPOFOL 10mg/ml 20ml',:forma_id=>2,:controlado=>true)
Farmaco.create(:farmaco=>'SEVOFLURANO 200ml',:forma_id=>4,:controlado=>true)
Farmaco.create(:farmaco=>'SEVOFLURANO 100ml',:forma_id=>4,:controlado=>true)
Farmaco.create(:farmaco=>'SUFENTANILA 5mcg/ml',:forma_id=>2,:controlado=>true)
Farmaco.create(:farmaco=>'TOPIRAMATO 50mg',:forma_id=>1,:controlado=>true)
Farmaco.create(:farmaco=>'TRAMADOL 50mg/ml',:forma_id=>2,:controlado=>true)
Farmaco.create(:farmaco=>'TRAMADOL 100mg/ml',:forma_id=>2,:controlado=>true)
Farmaco.create(:farmaco=>'TRAMADOL 50mg',:forma_id=>1,:controlado=>true)
Farmaco.create(:farmaco=>'TRIPTANOL 25mg',:forma_id=>4,:controlado=>true)
