common:
  project: FarmaControl 344
  email_from: rayponet@yahoo.com.br
  email_help: rayponet@yahoo.com.br

production:
  host_addr: http://www.lipsiasoft.com

development:
  host_addr: http://localhost:3000
  
test:
  host_addr: http://localhost:3000